version: "3.8"

services:
  db:
    image: postgres:14
    container_name: cme_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cme_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./cme-backend
    container_name: cme_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cme_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./cme-frontend
    container_name: cme_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

